# -*- ruby encoding: utf-8 -*-

require "rubygems"
require "hoe"

Hoe.plugin :minitest

Hoe.spec "reset" do
  developer("Farhan Hurmoodi", "fhurmoodi@gmail.com")
  license 'MIT'
end

# vim: syntax=ruby
